# Generated by Django 5.2.8 on 2026-09-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='value',
            field=models.TextField(),
        ),
    ]
