web: python manage.py migrate && python manage.py collectstatic --noinput && python manage.py superuser --username admin --email admin@ssct.edu.ph --password Passw0rd! --no-input || true && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --worker-class gthread --threads 2 --timeout 120 --access-logfile - --error-logfile -

