"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
from django.core.cache import cache
from urllib.parse import urlparse
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Repo root .env (E_Botar/.env), then backend/.env — latter overrides when both exist
load_dotenv(BASE_DIR.parent / '.env')
load_dotenv(BASE_DIR / '.env', override=True)

IS_PRODUCTION = os.getenv('IS_PRODUCTION', 'False').lower() == 'true'

SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if IS_PRODUCTION:
        raise ValueError(
            "SECRET_KEY environment variable must be set in production! "
            "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
        )
    # Fallback for local development only
    SECRET_KEY = 'django-insecure-c^hu1q77a4tnn$dil=sboisr6kk78)&w^99*6l#(_+z^!t&))6'
    import warnings
    warnings.warn(
        "Using insecure default SECRET_KEY. Set SECRET_KEY environment variable for production!",
        UserWarning
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1']

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Convert Cloudinary upload failures to a friendly 503 with
    # detail = "Unavailable at the moment." (see apps.common.http.exception_handlers).
    "EXCEPTION_HANDLER": "apps.common.http.exception_handlers.media_aware_exception_handler",
    # DRF Throttling (used for sensitive endpoints like vote submission and form posts)
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        # Global per-user limit (can be generous)
        "user": "1000/hour",
        # Specific scopes used by ScopedUserThrottle / enforce_scope_throttle.
        # DRF only supports 'second', 'minute', 'hour', 'day', so we approximate.
        "vote_submit": "3/minute",
        "registration_submit": "2/minute",
        "google_auth_submit": "10/minute",
        "application_submit": "6/minute",
        "program_submit": "15/minute",
        "program_import": "3/minute",
        "login_submit": "10/minute",
        "receipt_verify": "15/minute",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # DRF and third-party
    "rest_framework",
    "corsheaders",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    # Project apps
    "apps.accounts",
    "apps.elections",
    "apps.candidates",
    "apps.voting",
    "apps.common",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'apps.common.http.middleware.DynamicAllowedHostsMiddleware',  # Handle ALLOWED_HOSTS dynamically (platform-agnostic)
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files efficiently
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.common.http.middleware.SecurityLoggingMiddleware',  # Security logging
]

ROOT_URLCONF = 'backend.urls'

SITE_ID = int(os.getenv("SITE_ID", "1"))

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]

# Registration signup: acceptable email domains (comma- or semicolon-separated in env).
_registration_domains_default_parts = ('snsu.edu.ph', 'ssct.edu.ph')
_registration_domains_raw = os.getenv(
    'REGISTRATION_ALLOWED_EMAIL_DOMAINS',
    ','.join(_registration_domains_default_parts),
).strip()
REGISTRATION_ALLOWED_EMAIL_DOMAINS = tuple(
    part.strip().lower()
    for part in _registration_domains_raw.replace(';', ',').split(',')
    if part.strip()
) or _registration_domains_default_parts

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}

# Skip the intermediate allauth confirmation page and redirect directly to Google.
SOCIALACCOUNT_LOGIN_ON_GET = True

SOCIALACCOUNT_FORMS = {
    "signup": "apps.accounts.social_forms.GoogleSocialSignupForm",
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'backend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL on Railway, SQLite for local development
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Parse DATABASE_URL (Railway format: postgresql://user:password@host:port/dbname)
    parsed = urlparse(DATABASE_URL)
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed.path[1:],  # Remove leading '/'
            'USER': parsed.username,
            'PASSWORD': parsed.password,
            'HOST': parsed.hostname,
            'PORT': parsed.port or '5432',
            'OPTIONS': {
                'sslmode': 'require',
            },
        }
    }
else:
    # Local development - use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-ebotar-cache",
        "TIMEOUT": None,      # use cache.set timeout values (None = never expire)
        "OPTIONS": {
            "MAX_ENTRIES": 300,  # tweak if you want more/less entries per process
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ---------------------------------------------------------------------------
# Storage backends
# ---------------------------------------------------------------------------
# Default media storage is local filesystem. When Cloudinary credentials are
# present (CLOUDINARY_URL or CLOUDINARY_CLOUD_NAME), uploads are stored on
# Cloudinary so they survive ephemeral redeploys (e.g., Railway).
# ---------------------------------------------------------------------------
CLOUDINARY_URL = os.getenv('CLOUDINARY_URL', '').strip()
CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME', '').strip()
USE_CLOUDINARY_MEDIA = bool(CLOUDINARY_URL or CLOUDINARY_CLOUD_NAME)

# Cloudinary folder that all E-Botar uploads are placed under, so the project's
# assets stay grouped (e.g. "E-Botar/profile_photos/...") instead of polluting
# the root of the Cloudinary Media Library. Set to empty to disable prefixing.
CLOUDINARY_MEDIA_FOLDER = os.getenv('CLOUDINARY_FOLDER', 'E-Botar').strip()

if USE_CLOUDINARY_MEDIA:
    INSTALLED_APPS += ['cloudinary', 'cloudinary_storage']
    if not CLOUDINARY_URL:
        CLOUDINARY_STORAGE = {
            'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
            'API_KEY': os.getenv('CLOUDINARY_API_KEY', ''),
            'API_SECRET': os.getenv('CLOUDINARY_API_SECRET', ''),
        }
    # Resilient wrapper converts Cloudinary upload errors into MediaUploadUnavailable
    # so the DRF exception handler can return a friendly 503 instead of a 500.
    # django-cloudinary-storage keeps its default PREFIX (= settings.MEDIA_URL,
    # i.e. "media/") so the public IDs mirror the local-filesystem layout and
    # the project can be flipped back to local storage without renaming
    # anything in Cloudinary.
    _DEFAULT_FILE_STORAGE_BACKEND = 'apps.common.files.storage.ResilientMediaCloudinaryStorage'
else:
    _DEFAULT_FILE_STORAGE_BACKEND = 'django.core.files.storage.FileSystemStorage'

STORAGES = {
    'default': {
        'BACKEND': _DEFAULT_FILE_STORAGE_BACKEND,
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

BACKEND_BASE_URL = os.getenv('BACKEND_BASE_URL', None)
API_VERSION = os.getenv('API_VERSION', 'v1')
BACKEND_VERSION = os.getenv('BACKEND_VERSION', '3.0')
MIN_FRONTEND_VERSION = os.getenv('MIN_FRONTEND_VERSION', '3.0')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration - Dynamic and platform-agnostic

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Security settings for production

SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# HSTS settings
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

