# Generated by Django 5.2.8 on 2026-05-07 12:43

import apps.common.files.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.files.upload_paths.candidate_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.files.upload_paths.candidate_photo_upload_path),
        ),
    ]
