# Generated by Django 5.2.8 on 2026-10-03 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_photo_and_more'),
        ('elections', '0006_alter_schoolelection_is_paused'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['election', 'is_active', 'position'], name='cand_election_active_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateapplication',
            index=models.Index(fields=['election', 'status'], name='cand_app_election_status_idx'),
        ),
    ]
