# Generated by Django 5.2.8 on 2025-11-28 02:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text="Program code (e.g., 'CS', 'BSCS')", max_length=20)),
                ('program_type', models.CharField(choices=[('department', 'Department'), ('course', 'Course')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of the program')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Assign department for course-type programs', limit_choices_to={'program_type': 'department'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.program')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'accounts_program',
                'ordering': ['program_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, help_text='Format: XXXX-XXXXX where XXXX is year created and XXXXX is random/indexed (e.g., 2024-12345)', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_student_id', message='Student ID must be in format XXXX-XXXXX where XXXX is year created and XXXXX is random/indexed (e.g., 2024-12345)', regex='^\\d{4}-\\d{5}$')])),
                ('year_level', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, limit_choices_to={'program_type': 'course'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_students', to='accounts.program')),
                ('department', models.ForeignKey(blank=True, limit_choices_to={'program_type': 'department'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_students', to='accounts.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'accounts_userprofile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('program_type', 'code'), name='unique_program_code_per_type'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('program_type', 'name'), name='unique_program_name_per_type'),
        ),
    ]
