# Generated by Django 5.2.8 on 2026-05-03 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Optional college/department for course-type rows (by code). Leave empty when unassigned (e.g. reorganizations).', limit_choices_to={'program_type': 'department'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.program', to_field='code'),
        ),
    ]
