# Generated by Django 5.2.8 on 2026-05-07 12:43

import apps.common.files.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_program_department_optional_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.files.upload_paths.avatar_upload_path),
        ),
    ]
