# Generated by Django 5.2.8 on 2025-11-10 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('receipt_hash', models.CharField(db_index=True, help_text='SHA-256 hash of receipt for verification', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address for audit trail', null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='elections.schoolelection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote Receipt',
                'verbose_name_plural': 'Vote Receipts',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'election')},
            },
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent', max_length=255)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='elections.schoolelection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ballot', to='voting.votereceipt')),
            ],
            options={
                'verbose_name': 'Ballot',
                'verbose_name_plural': 'Ballots',
                'ordering': ['-submitted_at'],
                'unique_together': {('user', 'election')},
            },
        ),
        migrations.CreateModel(
            name='AnonVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_hash', models.CharField(db_index=True, help_text='Hash for vote verification', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anon_votes', to='candidates.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anon_votes', to='elections.schoolelection')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anon_votes', to='elections.schoolposition')),
            ],
            options={
                'verbose_name': 'Anonymous Vote',
                'verbose_name_plural': 'Anonymous Votes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['election', 'position', 'candidate'], name='voting_anon_electio_432360_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoteChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anonymized', models.BooleanField(default=False, help_text='Whether this choice has been converted to AnonVote')),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='voting.ballot')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.schoolposition')),
            ],
            options={
                'verbose_name': 'Vote Choice',
                'verbose_name_plural': 'Vote Choices',
                'ordering': ['position__display_order'],
                'unique_together': {('ballot', 'position')},
            },
        ),
    ]
