# Generated by Django 5.2.8 on 2025-11-10 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='party_logos/')),
                ('color', models.CharField(default='#0b6e3b', help_text='Hex color code for party branding', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position_type', models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('auditor', 'Auditor'), ('public_info', 'Public Information Officer'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('max_candidates', models.PositiveIntegerField(default=10, help_text='Maximum number of candidates allowed for this position')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Position',
                'verbose_name_plural': 'School Positions',
                'ordering': ['display_order', 'position_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_year', models.IntegerField(blank=True, help_text='Start year for SY format (e.g., 2025 for SY 2025-2026)', null=True)),
                ('end_year', models.IntegerField(blank=True, help_text='End year for SY format (e.g., 2026 for SY 2025-2026)', null=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Election',
                'verbose_name_plural': 'School Elections',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ElectionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order for this position in the election')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this position is active for voting in this election')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_positions', to='elections.schoolelection')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_elections', to='elections.schoolposition')),
            ],
            options={
                'verbose_name': 'Election Position',
                'verbose_name_plural': 'Election Positions',
                'ordering': ['order', 'position__display_order'],
                'unique_together': {('election', 'position')},
            },
        ),
    ]
