# Generated by Django 5.2.8 on 2026-05-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_schoolelection_is_paused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolelection',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='When True, voting is temporarily suspended while keeping published schedule.'),
        ),
    ]
