# Generated by Django 5.2.8 on 2026-10-03 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_must_change_password_and_more'),
        ('elections', '0006_alter_schoolelection_is_paused'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schoolelection',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='election_schedule_idx'),
        ),
    ]
